#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 24 20:54:05 2022

@author: skye
"""

# the screen / map
import pygame
pygame.init()
dis=pygame.display.set_mode((1280,720))
pygame.display.update()
game_over = False
while not game_over:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            game_over = True
pygame.quit()
quit()

# the blocks
import pygame
import time
import random

pygame.init()

white, (225, 225, 225)
black = (0, 0, 0)
pink = (0, 0 ,0 )
 
dis_width = 800
dis_height = 600

block = 10
 
dis = pygame.display.set_mode((dis_width, dis_height))
 
clock = pygame.time.Clock()
 
black_blocks = 10
pink_blocks = 10

font_style = pygame.font.SysFont(None, 30)

def message(msg, color):
    mesg = font_style.render(msg, True, color)
    dis.blit(mesg, [dis_width/3, dis_height/3])
 
 
def gameLoop():
    game_over = False
    game_close = False
 
    x1 = dis_width / 2
    y1 = dis_height / 2
 
    x1_change = 0
    y1_change = 0
 
    blockx = round(random.randrange(0, dis_width - block) / 10.0) * 10.0
    blocky = round(random.randrange(0, dis_width - block) / 10.0) * 10.0
 
    while not game_over:
 
        while game_close == True:
            dis.fill(white)
            message("You Lost! Press Q-Quit or C-Play Again", red)
            pygame.display.update()
 
            for event in pygame.event.get():
                if event.type == pygame.KEYDOWN:
                    if event.key == pygame.K_q:
                        game_over = True
                        game_close = False
                    if event.key == pygame.K_c:
                        gameLoop()
 
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                game_over = True
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_LEFT:
                    x1_change = -block
                    y1_change = 0
                elif event.key == pygame.K_RIGHT:
                    x1_change = block
                    y1_change = 0
                elif event.key == pygame.K_UP:
                    y1_change = -block
                    x1_change = 0
                elif event.key == pygame.K_DOWN:
                    y1_change = block
                    x1_change = 0
 
        if x1 >= dis_width or x1 < 0 or y1 >= dis_height or y1 < 0:
            game_close = True
 
        x1 += x1_change
        y1 += y1_change
        dis.fill(white)
        pygame.draw.rect(dis, pink, [blockx, blocky, block, block])
        pygame.draw.rect(dis, black, [x1, y1, block, block])
        pygame.display.update()
 
        if x1 == blockx and y1 == blocky:
            print("Yummy!!")
 
    pygame.quit()
    quit()
 
 
gameLoop()

#the score display
import pygame
import time
import random
 
pygame.init()
 
black = (0, 0, 0)
pink = (0, 0, 0)
 
dis_width = 600
dis_height = 400
 
dis = pygame.display.set_mode((dis_width, dis_height))
 
clock = pygame.time.Clock()
 
block = 10
 
font_style = pygame.font.SysFont("bahnschrift", 25)
score_font = pygame.font.SysFont("comicsansms", 35)
 
 
def score(score):
    value = score_font.render("Score: " + str(score), True, black)
    dis.blit(value, [0, 0])
 
